# Generated by Django 3.2.12 on 2022-03-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='names',
            field=models.CharField(default='none', max_length=211, null=True),
        ),
    ]
