# Generated by Django 3.2.12 on 2022-04-03 17:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0007_reviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contacts',
            new_name='postss',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='host',
            new_name='person_reviewed',
        ),
    ]
